-- ─── phases ──────────────────────────────────────────────────
INSERT INTO `phases`
    (`id`, `phase_num`, `ten_phase`, `saga`, `years`, `mo_ta`, `film_count`, `phase_hue`)
VALUES
(1, 1, 'The Beginning',      'Infinity Saga',   '2008 – 2012', 'Khởi đầu vũ trụ với Iron Man, Thor, Hulk và cuộc hội tụ Avengers đầu tiên.', 6, 0),
(2, 2, 'Expansion',          'Infinity Saga',   '2013 – 2015', 'Mở rộng vũ trụ với Guardians of the Galaxy và những mối đe dọa mới.', 6, 20),
(3, 3, 'The Infinity War',   'Infinity Saga',   '2016 – 2019', 'Thanos — cuộc chiến Infinity War và Endgame thay đổi vũ trụ mãi mãi.', 10, 340),
(4, 4, 'New World',          'Multiverse Saga', '2021 – 2022', 'Hậu Endgame — multiverse mở ra, những anh hùng mới trỗi dậy.', 7, 200),
(5, 5, 'The Kang Dynasty',   'Multiverse Saga', '2023 – 2024', 'Kang the Conqueror và mối đe dọa xuyên thời gian.', 4, 260),
(6, 6, 'Secret Wars',        'Multiverse Saga', '2025 – 2026', 'Avengers: Secret Wars — cuộc hội tụ vĩ đại nhất lịch sử MCU.', 4, 170);

-- ─── movies ──────────────────────────────────────────────────
INSERT INTO `movies`
    (`id`, `slug`, `title`, `year`, `duration`, `rating`, `box_office`, `director`, `cast_list`, `description`, `tagline`, `bg_color`, `poster_url`, `type`, `view_order`, `phase_id`)
VALUES
-- Phase 1
(1, 'iron-man', 'Iron Man', 2008, '126 phút', 8.0, '$585M', 'Jon Favreau', 'Robert Downey Jr., Gwyneth Paltrow, Terrence Howard', 'Tony Stark chế tạo bộ giáp đầu tiên để thoát khỏi tù giam và trở thành Iron Man.', 'Genius. Billionaire. Playboy. Philanthropist.', '#C0392B', '', 'movie', 1, 1),
(2, 'incredible-hulk', 'The Incredible Hulk', 2008, '112 phút', 6.7, '$264M', 'Louis Leterrier', 'Edward Norton, Liv Tyler, Tim Roth', 'Bruce Banner cố kiềm chế Hulk trong khi bị quân đội truy đuổi. Abomination nổi dậy.', 'This is not who I am.', '#27AE60', '', 'movie', 2, 1),
(3, 'iron-man-2', 'Iron Man 2', 2010, '124 phút', 7.0, '$624M', 'Jon Favreau', 'Robert Downey Jr., Mickey Rourke, Gwyneth Paltrow', 'Tony phải đối mặt với chính phủ, kẻ thù mới Whiplash, và chất độc palladium.', 'I am Iron Man.', '#E74C3C', '', 'movie', 3, 1),
(4, 'thor', 'Thor', 2011, '115 phút', 7.0, '$449M', 'Kenneth Branagh', 'Chris Hemsworth, Natalie Portman, Tom Hiddleston', 'Thor bị trục xuất khỏi Asgard xuống Trái Đất, phải chứng minh bản thân xứng đáng cầm búa Mjolnir.', 'Two worlds. One hero.', '#1A5276', '', 'movie', 4, 1),
(5, 'captain-america-first-avenger', 'Captain America: The First Avenger', 2011, '124 phút', 7.3, '$371M', 'Joe Johnston', 'Chris Evans, Hayley Atwell, Hugo Weaving', 'Steve Rogers trở thành Super-Soldier, chiến đấu chống lại HYDRA và Red Skull trong Thế chiến II.', 'Not a perfect soldier, but a good man.', '#154360', '', 'movie', 5, 1),
(6, 'avengers', 'The Avengers', 2012, '143 phút', 8.0, '$1.520B', 'Joss Whedon', 'Robert Downey Jr., Chris Evans, Chris Hemsworth', 'Đội hình Avengers đầu tiên hội tụ bảo vệ Trái Đất khỏi cuộc xâm lăng của phân đội Chitauri do Loki dẫn đầu.', 'There was an idea...', '#1A2980', '', 'movie', 6, 1),

-- Phase 2
(7, 'iron-man-3', 'Iron Man 3', 2013, '130 phút', 7.1, '$1.215B', 'Shane Black', 'Robert Downey Jr., Gwyneth Paltrow, Guy Pearce', 'Sau sự kiện New York, Tony Stark đối mặt với Mandarin và Extremis.', 'We make our own demons.', '#922B21', '', 'movie', 7, 2),
(8, 'thor-dark-world', 'Thor: The Dark World', 2013, '112 phút', 6.8, '$644M', 'Alan Taylor', 'Chris Hemsworth, Natalie Portman, Tom Hiddleston', 'Thor phải hợp tác với Loki để ngăn chặn tộc Dark Elf hủy diệt vũ trụ bằng Reality Stone.', 'Two worlds colliding.', '#4A235A', '', 'movie', 8, 2),
(9, 'captain-america-winter-soldier', 'Captain America: The Winter Soldier', 2014, '136 phút', 7.8, '$714M', 'Anthony Russo, Joe Russo', 'Chris Evans, Scarlett Johansson, Sebastian Stan', 'Steve Rogers khám phá ra SHIELD đã bị HYDRA thâm nhập, và đối mặt với sát thủ Winter Soldier.', 'In heroes we trust.', '#1B4F72', '', 'movie', 9, 2),
(10, 'guardians-of-the-galaxy', 'Guardians of the Galaxy', 2014, '121 phút', 8.0, '$773M', 'James Gunn', 'Chris Pratt, Zoe Saldana, Dave Bautista', 'Một nhóm tội phạm không gian phải hợp tác để ngăn chặn Ronan phá hủy hành tinh Xandar.', 'We are Groot.', '#6D4C8E', '', 'movie', 10, 2),
(11, 'avengers-age-of-ultron', 'Avengers: Age of Ultron', 2015, '141 phút', 7.3, '$1.405B', 'Joss Whedon', 'Robert Downey Jr., Chris Evans, Chris Hemsworth', 'Tony Stark tạo ra AI Ultron, nhưng nó quyết định tiêu diệt nhân loại.', 'There are no strings on me.', '#2C3E50', '', 'movie', 11, 2),
(12, 'ant-man', 'Ant-Man', 2015, '117 phút', 7.3, '$519M', 'Peyton Reed', 'Paul Rudd, Michael Douglas, Evangeline Lilly', 'Tên trộm Scott Lang sử dụng bộ đồ thu nhỏ của Hank Pym để thực hiện một vụ trộm giải cứu thế giới.', 'Heroes don''t get any bigger.', '#7B241C', '', 'movie', 12, 2),

-- Phase 3
(13, 'captain-america-civil-war', 'Captain America: Civil War', 2016, '147 phút', 7.8, '$1.153B', 'Anthony Russo, Joe Russo', 'Chris Evans, Robert Downey Jr., Scarlett Johansson', 'Hiệp định Sokovia chia rẽ Avengers thành hai phe đối lập do Cap và Iron Man dẫn đầu.', 'United we stand. Divided we fall.', '#2E4057', '', 'movie', 13, 3),
(14, 'doctor-strange', 'Doctor Strange', 2016, '115 phút', 7.5, '$677M', 'Scott Derrickson', 'Benedict Cumberbatch, Chiwetel Ejiofor, Rachel McAdams', 'Bác sĩ phẫu thuật Stephen Strange học phép thuật và bảo vệ Trái Đất khỏi các thế lực thần bí.', 'Open your mind.', '#F39C12', '', 'movie', 14, 3),
(15, 'guardians-of-the-galaxy-vol-2', 'Guardians of the Galaxy Vol. 2', 2017, '136 phút', 7.6, '$863M', 'James Gunn', 'Chris Pratt, Zoe Saldana, Dave Bautista', 'Nhóm Guardians khám phá nguồn gốc thực sự của Peter Quill và đối mặt với Ego.', 'Obviously.', '#884EA0', '', 'movie', 15, 3),
(16, 'spider-man-homecoming', 'Spider-Man: Homecoming', 2017, '133 phút', 7.4, '$880M', 'Jon Watts', 'Tom Holland, Michael Keaton, Robert Downey Jr.', 'Peter Parker cố gắng cân bằng cuộc sống học đường và trách nhiệm siêu anh hùng dưới sự giám sát của Tony Stark.', 'Homework can wait. The city can''t.', '#CB4335', '', 'movie', 16, 3),
(17, 'thor-ragnarok', 'Thor: Ragnarok', 2017, '130 phút', 7.9, '$853M', 'Taika Waititi', 'Chris Hemsworth, Tom Hiddleston, Cate Blanchett', 'Thor bị đày đến Sakaar và phải tham gia đấu trường giác đấu để trở về cứu Asgard khỏi Hela.', 'No hammer. No problem.', '#A569BD', '', 'movie', 17, 3),
(18, 'black-panther', 'Black Panther', 2018, '134 phút', 7.3, '$1.347B', 'Ryan Coogler', 'Chadwick Boseman, Michael B. Jordan, Lupita Nyong''o', 'T''Challa trở về Wakanda để lên ngôi vua nhưng phải đối mặt với Killmonger.', 'Wakanda Forever.', '#1A237E', '', 'movie', 18, 3),
(19, 'avengers-infinity-war', 'Avengers: Infinity War', 2018, '149 phút', 8.4, '$2.048B', 'Anthony Russo, Joe Russo', 'Robert Downey Jr., Chris Evans, Chris Hemsworth', 'Thanos thu thập 6 viên đá Vô Cực để thực hiện cú búng tay xóa sổ một nửa sinh linh vũ trụ.', 'An entire universe. Once and for all.', '#4A235A', '', 'movie', 19, 3),
(20, 'captain-marvel', 'Captain Marvel', 2019, '123 phút', 6.8, '$1.128B', 'Anna Boden, Ryan Fleck', 'Brie Larson, Samuel L. Jackson, Ben Mendelsohn', 'Carol Danvers trở thành một trong những anh hùng mạnh nhất vụ trụ khi Trái Đất bị cuốn vào cuộc chiến giữa hai tộc người ngoài hành tinh.', 'Higher. Further. Faster.', '#C0392B', '', 'movie', 20, 3),
(21, 'avengers-endgame', 'Avengers: Endgame', 2019, '181 phút', 8.4, '$2.798B', 'Anthony Russo, Joe Russo', 'Robert Downey Jr., Chris Evans, Chris Hemsworth', 'Các Avengers sống sót quay ngược thời gian để thu thập đá Vô Cực và đảo ngược cú búng tay của Thanos.', 'Whatever it takes.', '#0D0D0D', '', 'movie', 21, 3),
(22, 'spider-man-far-from-home', 'Spider-Man: Far From Home', 2019, '129 phút', 7.4, '$1.131B', 'Jon Watts', 'Tom Holland, Samuel L. Jackson, Jake Gyllenhaal', 'Hậu Endgame, Peter Parker đến châu Âu du lịch nhưng bị Nick Fury chiêu mộ để đối đầu với nhóm Elementals.', 'It''s time to step up.', '#2874A6', '', 'movie', 22, 3),

-- Phase 4
(23, 'black-widow', 'Black Widow', 2021, '134 phút', 6.7, '$379M', 'Cate Shortland', 'Scarlett Johansson, Florence Pugh, David Harbour', 'Natasha Romanoff đối mặt với quá khứ đen tối của mình và tổ chức Red Room.', 'She''s done running from her past.', '#641E16', '', 'movie', 23, 4),
(24, 'shang-chi', 'Shang-Chi and the Legend of the Ten Rings', 2021, '132 phút', 7.4, '$432M', 'Destin Daniel Cretton', 'Simu Liu, Awkwafina, Tony Leung', 'Shang-Chi phải đối mặt với quá khứ và di sản gia đình khi anh bị cuốn vào tổ chức Ten Rings.', 'A Marvel Legend Will Rise.', '#9C640C', '', 'movie', 24, 4),
(25, 'eternals', 'Eternals', 2021, '156 phút', 6.3, '$402M', 'Chloé Zhao', 'Gemma Chan, Richard Madden, Angelina Jolie', 'Tộc người bất tử Eternals bước ra khỏi bóng tối để bảo vệ Trái Đất khỏi các Deviants.', 'In the beginning...', '#D4AC0D', '', 'movie', 25, 4),
(26, 'spider-man-no-way-home', 'Spider-Man: No Way Home', 2021, '148 phút', 8.2, '$1.921B', 'Jon Watts', 'Tom Holland, Zendaya, Benedict Cumberbatch', 'Peter Parker nhờ Doctor Strange xóa ký ức mọi người, nhưng phép thuật lỗi làm vỡ Đa vũ trụ.', 'Multiverse unleashed.', '#E74C3C', '', 'movie', 26, 4),
(27, 'doctor-strange-multiverse', 'Doctor Strange in the Multiverse of Madness', 2022, '126 phút', 6.9, '$955M', 'Sam Raimi', 'Benedict Cumberbatch, Elizabeth Olsen, Xochitl Gomez', 'Doctor Strange hợp tác cùng America Chavez để chạy trốn khỏi sự truy sát của Scarlet Witch qua Đa vũ trụ.', 'Enter a new dimension of Strange.', '#7B241C', '', 'movie', 27, 4),
(28, 'thor-love-and-thunder', 'Thor: Love and Thunder', 2022, '119 phút', 6.2, '$760M', 'Taika Waititi', 'Chris Hemsworth, Natalie Portman, Christian Bale', 'Thor hợp tác với Jane Foster (Mighty Thor) để đánh bại Gorr the God Butcher.', 'The one and only.', '#3498DB', '', 'movie', 28, 4),
(29, 'black-panther-wakanda-forever', 'Black Panther: Wakanda Forever', 2022, '161 phút', 6.7, '$859M', 'Ryan Coogler', 'Letitia Wright, Lupita Nyong''o, Tenoch Huerta', 'Wakanda tang thương sau cái chết của vua T''Challa và phải đối mặt với vương quốc Talokan dưới biển sâu do Namor lãnh đạo.', 'Forever.', '#1A237E', '', 'movie', 29, 4),

-- Phase 5
(30, 'ant-man-quantumania', 'Ant-Man and the Wasp: Quantumania', 2023, '125 phút', 6.1, '$476M', 'Peyton Reed', 'Paul Rudd, Evangeline Lilly, Jonathan Majors', 'Scott Lang cùng gia đình bị kéo vào Lượng Tử Giới và đối mặt với Kang the Conqueror.', 'Witness the beginning of a new dynasty.', '#1F618D', '', 'movie', 30, 5),
(31, 'guardians-vol-3', 'Guardians of the Galaxy Vol. 3', 2023, '150 phút', 7.9, '$845M', 'James Gunn', 'Chris Pratt, Zoe Saldana, Chukwudi Iwuji', 'Nhóm Guardians đối mặt với High Evolutionary để cứu lấy mạng sống của Rocket.', 'Once more with feeling.', '#922B21', '', 'movie', 31, 5),
(32, 'the-marvels', 'The Marvels', 2023, '105 phút', 5.5, '$206M', 'Nia DaCosta', 'Brie Larson, Teyonah Parris, Iman Vellani', 'Sức mạnh của Captain Marvel, Monica Rambeau và Ms. Marvel bị tráo đổi, buộc họ phải hợp tác giải quyết sự cố.', 'Higher. Further. Faster. Together.', '#A569BD', '', 'movie', 32, 5),
(33, 'deadpool-and-wolverine', 'Deadpool & Wolverine', 2024, '127 phút', 8.0, '$1.338B', 'Shawn Levy', 'Ryan Reynolds, Hugh Jackman, Emma Corrin', 'TVA bắt giữ Deadpool và ép anh hợp tác với biến thể Wolverine xui xẻo nhất để rẽ nhánh sự kiện cứu dòng thời gian của anh.', 'Best Bubs.', '#C0392B', '', 'movie', 33, 5),

-- Phase 6
(34, 'captain-america-brave-new-world', 'Captain America: Brave New World', 2025, '118 phút', 0.0, 'TBA', 'Julius Onah', 'Anthony Mackie, Harrison Ford, Giancarlo Esposito', 'Sam Wilson - Tân Đội trưởng Mỹ - phải đối phó với âm mưu toàn cầu cùng sự trỗi dậy của Red Hulk.', 'TBA', '#1A5276', '', 'movie', 34, 6),
(35, 'thunderbolts', 'Thunderbolts', 2025, 'TBA', 0.0, 'TBA', 'Jake Schreier', 'Sebastian Stan, Florence Pugh, David Harbour', 'Nhóm phản anh hùng của MCU, bao gồm Bucky Barnes, Yelena Belova và U.S. Agent được chính phủ tập hợp.', 'TBA', '#2E4057', '', 'movie', 35, 6),
(36, 'fantastic-four-first-steps', 'The Fantastic Four: First Steps', 2025, 'TBA', 0.0, 'TBA', 'Matt Shakman', 'Pedro Pascal, Vanessa Kirby, Joseph Quinn', 'Gia đình siêu anh hùng đầu tiên của Marvel ra mắt trong MCU, với bối cảnh thế giới tương lai-retro những năm 1960.', 'TBA', '#2E86C1', '', 'movie', 36, 6),
(37, 'avengers-doomsday', 'Avengers: Doomsday', 2026, 'TBA', 0.0, 'TBA', 'Anthony Russo, Joe Russo', 'Robert Downey Jr., Pedro Pascal', 'Cuộc đại chiến bản lề của Multiverse Saga với The Fantastic Four đối đầu cùng Victor Von Doom hay còn gọi là Doctor Doom.', 'Doom is inevitable.', '#1a1a1a', '', 'movie', 37, 6);
